kind: Service
apiVersion: v1
metadata:
  namespace: nas
  name: dissi-nasbox
spec:
  type: ExternalName
  externalName: dissi-nasbox.local
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nas
  namespace: nas
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/target: 86.84.170.207
    nginx.ingress.kubernetes.io/proxy-body-size: 50g
spec:
  tls:
  - secretName: home-letsencrypt-prod
    hosts:
    - home.dissi.me
  rules:
  - host: home.dissi.me
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: dissi-nasbox
              port:
                number: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foto-nas
  namespace: nas
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/target: 86.84.170.207
    nginx.ingress.kubernetes.io/proxy-body-size: 50g
spec:
  tls:
  - secretName: foto-letsencrypt-prod
    hosts:
    - foto.dissi.me
  rules:
  - host: foto.dissi.me
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: dissi-nasbox
              port:
                number: 5080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homelinks
  namespace: nas
  annotations: 
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/target: 86.84.170.207
spec:
  tls:
  - secretName: links-letsencrypt-prod
    hosts:
    - dissi.me
  rules:
  - host: dissi.me
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: dissi-nasbox
              port:
                number: 5002
