# https://hub.docker.com/r/homeassistant/home-assistant/tags?page=1&ordering=last_updated
image:
  repository: homeassistant/home-assistant
  tag: "2023.3"

mariadb:
  enabled: false

postgresql:
  enabled: false

influxdb:
  enabled: false

ingress:
  main:
    enabled: true  
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.org/websocket-services: home-home-assistant
      external-dns.alpha.kubernetes.io/target: 86.84.170.207
    tls: 
      - secretName: home-assistant-letsencrypt-prod
        hosts:
        - connect.dissi.me
    hosts:
      - host: connect.dissi.me
        paths:
        - path: /
          pathType: Prefix
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: cluster.dissi.me/ha
          operator: In
          values:
          - "true"
securityContext:
  privileged: true
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
persistence:
  config:
    enabled: true
    existingClaim: nas-config
    mountPath: /config
    subPath: home-assistant
  rts:
    enabled: true
    type: hostPath
    hostPath: /dev/ttyUSB0
    medium: CharDevice

service:
  main:
    hostNetwork: true
    ports:
      http:
        port: 8123
  weather:
    enabled: true
    type: NodePort
    ports:
      tcp:
        enabled: true
        port: 31000
        nodePort: 31000
  sonos:
    enabled: true
    ports:
      sonos:
        enabled: true
        port: 1400
        protocol: TCP
