image:
  # https://github.com/linuxserver/docker-plex
  tag: latest
  repository: lscr.io/linuxserver/plex
persistence:
  config:
    enabled: true
    existingClaim: nas-config
    mountPath: /config
    subPath: plex
common:
  persistence:
    host-dev:
      enabled: true
      existingClaim: nas-media
      mountPath: /media
ingress:
  main:
    enabled: true
    annotations: 
      nginx.org/proxy-send-timeout: 120m
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/target: 86.84.170.207
      nginx.ingress.kubernetes.io/proxy-buffering: "off"
      nginx.org/websocket-services: plex
    tls: 
      - secretName: plex-letsencrypt-prod
        hosts:
        - plex.dissi.me
    hosts:
      - host: plex.dissi.me
        paths:
        - path: /
          pathType: Prefix

env:
  PLEX_CLAIM: # Get from https://www.plex.tv/claim/
  VERSION: docker

resources:
  requests:
    cpu: 2000m
    memory: 4096Mi
    gpu.intel.com/i915: 1
  limits:
    cpu: 8000m
    memory: 6144Mi
    gpu.intel.com/i915: 1