apiVersion: v1
kind: PersistentVolume
metadata:
  name: nasbox-nfs-pv-maria
spec:
  capacity:
    storage: 1260Gi 
  volumeMode: Filesystem
  storageClassName: nfs-maria
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
  nfs: 
    path: /volume3/containerstorage/home/maria
    server: 192.168.2.100
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-maria
spec:
  storageClassName: nfs-maria
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "10Gi"
