apiVersion: v1
kind: PersistentVolume
metadata:
  name: nasbox-nfs-pv-cache
spec:
  capacity:
    storage: 2200Gi 
  volumeMode: Filesystem
  storageClassName: nfs-cache
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=4
  nfs: 
    path: /volume1/lancache
    server: 192.168.2.100
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: lancache
  name: nas-cache
spec:
  storageClassName: nfs-cache
  accessModes:
    - "ReadWriteMany"
  resources:
    requests:
      storage: "2200Gi"
      