image:
  # https://hub.docker.com/r/linuxserver/radarr
  tag: latest
  repository: lscr.io/linuxserver/radarr
persistence:
  config:
    enabled: true
    existingClaim: nas-config
    mountPath: /config
    subPath: radarr
  media:
    enabled: true
    existingClaim: nas-media
ingress:
  main:
    enabled: true
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.2.0/22,10.100.0.0/24"
      external-dns.alpha.kubernetes.io/target: 86.82.75.36
    tls: 
      - secretName: radarr-letsencrypt-prod
        hosts:
        - film.dissi.me
    hosts:
      - host: film.dissi.me
        paths:
        - path: /
          pathType: Prefix
