image:
  # https://hub.docker.com/r/linuxserver/radarr
  tag: latest
  repository: lscr.io/linuxserver/radarr
persistence:
  config:
    enabled: true
    existingClaim: nas-config
    mountPath: /config
    subPath: radarr
  media:
    enabled: true
    existingClaim: nas-media
ingress:
  main:
    enabled: true
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.2.0/23,10.100.0.0/24"
      external-dns.alpha.kubernetes.io/target: 86.84.170.207
    tls: 
      - secretName: radarr-letsencrypt-prod
        hosts:
        - film.dissi.me
    hosts:
      - host: film.dissi.me
        paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 500m
    memory: 1024Mi
  limits:
    cpu: 2000m
    memory: 2048Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/arch
          operator: In
          values:
          - amd64
          - arm64
