# https://hub.docker.com/r/linuxserver/sabnzbd
image:
  tag: latest
  repository: lscr.io/linuxserver/sabnzbd

persistence:
  config:
    enabled: true
    existingClaim: nas-config
    subPath: sabnzdb
    skipuninstall: true
  media:
    enabled: true
    existingClaim: nas-media
    skipuninstall: true

ingress:
  main:
    enabled: true
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.2.0/22,10.100.0.0/24"
      external-dns.alpha.kubernetes.io/target: 86.82.75.36
    tls: 
      - secretName: sabnzdb-letsencrypt-prod
        hosts:
        - sabnzbd.dissi.me
    hosts:
      - host: sabnzbd.dissi.me
        paths:
        - path: /
          pathType: Prefix