apiVersion: v1
kind: Service
metadata:
  name: {{ include "lancachedns.fullname" . }}-tcp
  labels:
    {{- include "lancachedns.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ .Values.dns.ip }}
    metallb.universe.tf/allow-shared-ip: {{ include "lancachedns.fullname" . }}
spec:
  type: LoadBalancer
  ports:
    - port: 53
      targetPort: http
      protocol: TCP
      name: tcp
  selector:
    {{- include "lancachedns.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lancachedns.fullname" . }}-udp
  labels:
    {{- include "lancachedns.labels" . | nindent 4 }}
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ .Values.dns.ip }}
    metallb.universe.tf/allow-shared-ip: {{ include "lancachedns.fullname" . }}
spec:
  type: LoadBalancer
  ports:
    - port: 53
      targetPort: udp
      protocol: UDP
      name: udp
  selector:
    {{- include "lancachedns.selectorLabels" . | nindent 4 }}
